# Generated by Django 3.2.9 on 2021-12-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('catagory', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
